Generate 100 particle sizes in RANDOM
cbgeo-learn/qiuyu pull request #1
Opened 2019-09-13 21:39 UTC by Amber1995

2019-09-13 21:42 UTC, kks32 requested changes
Could you please fix these

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +#include <stdlib.h>
```suggestion
#include <cstdlib>
```

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +#include <time.h>
```suggestion
#include <ctime> 
```

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +int main(void)
```suggestion
int main() {
```

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +{
```suggestion
```

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +srand((unsigned)time(NULL));
Use std::rand()

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +for(int i = 0; i < 100;i++ )
```suggestion
for(int i = 0; i < 100; ++i) 
```
Always preincreament

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +    std::cout << rand() / double(RAND_MAX) << std::endl;
I thought we wanted the radius to be between 2.0 and 4.0mm?

2019-09-13 21:42 UTC, kks32 commented on main.cc
> +return 0;
We don't need return 0 when `main` gets to this point it will return true (0)

2019-09-13 21:44 UTC, kks32 commented on main.cc
> +srand((unsigned)time(NULL));
https://en.cppreference.com/w/cpp/numeric/random/rand

2019-09-15 23:00 UTC, kks32 requested changes

2019-09-15 23:00 UTC, kks32 commented on main.cc
> +  double radius;
You can remove that, this is not `c` where you have to declare everything up front

2019-09-15 23:00 UTC, kks32 commented on main.cc
> +    radius = radius_a + 2.0 * std::rand() / double(RAND_MAX);
use `auto` 
```suggestion
    auto radius = radius_a + 2.0 * std::rand() / double(RAND_MAX);
```

2019-09-15 23:01 UTC, kks32 requested changes
Could you please create a vector of `radii` and append each new radius to that vector? 

Also could you please get the `n` number of `radii` needed from the user as an input. Just read it from commandline as an argument. Use `argc` and `argv` to parse commandline arguments.

2019-09-15 23:07 UTC, Amber1995 commented
Thanks for your suggestions！I will try to understand and make it. And as
soon as I finish it I will push it to GitHub.

See you tomorrow!

Qiuyu

Krishna Kumar <notifications@github.com>于2019年9月15日 周日下午6:02写道：

> *@kks32* requested changes on this pull request.
>
> Could you please create a vector of radii and append each new radius to
> that vector?
>
> Also could you please get the n number of radii needed from the user as
> an input. Just read it from commandline as an argument. Use argc and argv
> to parse commandline arguments.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cbgeo-learn/qiuyu/pull/1?email_source=notifications&email_token=ANA5SDIX3QT5HIJWN4HN4ZDQJ25GNA5CNFSM4IWUKLKKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCEYG2ZA#pullrequestreview-288386404>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANA5SDOC35XFMHDSXJ6NXILQJ25GNANCNFSM4IWUKLKA>
> .
>

2019-09-16 21:55 UTC, merged